# lab 02 - Numpy
Name: Robb Alexander    
Class: CSCI349    
Semester: 2021SP    
Instructor: Brian King


In [1]:
# Setting things up
import sys
import numpy as np
print(sys.version)
print(np.__version__)

3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ]
1.19.2



#### 1) Create a 52500 x 75 matrix of zeros, stored as X. Then, print out the shape of the matrix, the base data type, the individual item size in the array, and the total size of the array in bytes (as an integer). Also, print out the total size in megabytes with 3 significant digits.

In [146]:
X = np.zeros((52500,75))
print("X has shape of:", X.shape)
print("X has data type of:", X.dtype)
print("X has data type size of:", X.itemsize)
print("X has memory of:", X.nbytes, "bytes")
megabytes = X.nbytes / (1<<20)
print("X has memory of:",np.format_float_positional(megabytes, precision=3, fractional=False),"Megabytes")

X has shape of: (52500, 75)
X has data type of: float64
X has data type size of: 8
X has memory of: 31500000 bytes
X has memory of: 30.0 Megabytes


#### 2) Resize X to have the same number of elements, but with 100 columns. Show the shape. Show the number of bytes (which should be the same as the previous answer)

In [147]:
new_col = 100
new_row = X.size // new_col

X.resize((new_row, new_col))
print("X reshape has size of:", X.shape)
print("X reshape has memory of:", X.nbytes, "bytes")

X reshape has size of: (39375, 100)
X reshape has memory of: 31500000 bytes


#### 3) Redo #1, but use a base datatype of 16-bit integers.

In [148]:
X = np.zeros((52500,75), dtype="i2")
print("X has shape of:", X.shape)
print("X has data type of:", X.dtype)
print("X has data type size of:", X.itemsize)
print("X has memory of:", X.nbytes, "bytes")
megabytes = X.nbytes / (1<<20)
print("X has memory of:",np.format_float_positional(megabytes, precision=3, fractional=False),"Megabytes")

X has shape of: (52500, 75)
X has data type of: int16
X has data type size of: 2
X has memory of: 7875000 bytes
X has memory of: 7.51 Megabytes


#### 4) How many dimensions does X have? Answer using the appropriate property of np.ndarray objects.

In [149]:
print("X has dimension of:", len(X.shape))

X has dimension of: 2


#### 5) Enter the following Python list in your cell: str_nums = ['2.14', '-9.300', '42'] Convert this to a numpy array named X. What is the base type? Show the contents of X. Then, convert X to an array of single precision floating point numbers. (HINT: use astype). Show X again.

In [150]:
str_nums = ['2.14', '-9.300', '42']

X = np.array(str_nums)
print("X has dtype of:", X.dtype.name)
print("X has contents of:", X)

X = X.astype(float)
print("X has contents of:", X)

X has dtype of: str192
X has contents of: ['2.14' '-9.300' '42']
X has contents of: [ 2.14 -9.3  42.  ]


#### 6) Copy the three definitions above for the Python lists days, scores_1, and scores_2. Create a numpy array called scores that has scores_1 as the first row and scores_2 as the second row using np.concatenate. Then, change days into a np.array from the list days. Show the contents of scores and days, and output their shape.

In [151]:
days = ["Mon","Tue","Wed","Thu","Fri"]
scores_1 = [9.5, 8.75, 8, 10, 7.75]
scores_2 = [9, 8, 10, 8.75, 7.25]

scores = np.concatenate([[scores_1], [scores_2]])
print("scores has shape of:", scores.shape)
print("scores has contents of:")
print(scores,"\n")

days = np.array(days)
print("days has shape of:", days.shape)
print("days has contents of:")
print(days)

scores has shape of: (2, 5)
scores has contents of:
[[ 9.5   8.75  8.   10.    7.75]
 [ 9.    8.   10.    8.75  7.25]] 

days has shape of: (5,)
days has contents of:
['Mon' 'Tue' 'Wed' 'Thu' 'Fri']


#### 7) Repeat the previous problem with the creation of scores from the Python lists scores_1 and scores_2, but now do it with np.vstack. The array should be identical.

In [152]:
scores = np.vstack((scores_1, scores_2))
print("scores has shape of:", scores.shape)
print("scores has contents of:")
print(scores,"\n")

scores has shape of: (2, 5)
scores has contents of:
[[ 9.5   8.75  8.   10.    7.75]
 [ 9.    8.   10.    8.75  7.25]] 



#### 8) Compare the result of the expression days == "Fri" if the variable days was a Python list as entered above, vs. days being a numpy array. What is the difference in the result? In general, how does numpy deal with standard comparison operators?

In [156]:
days = ["Mon","Tue","Wed","Thu","Fri"]
print("python compare days = \"Fri\":", days == "Fri")

days = np.array(days)
print("numpy compare days = \"Fri\":", days == "Fri")

"""
The difference between the == operator is that python
  compares is the string is equal to the array itself
  While numpy compares if the string is contained in
  the np.array and creates the same dimensional array
  with the equality evaluation. Thus creating a bitmap
"""

python compare days = "Fri": False
numpy compare days = "Fri": [False False False False  True]


#### 9) Select the scores that fell on Monday.

In [157]:
print(scores[:,days == "Mon"])

[[9.5]
 [9. ]]


#### 10) Select all of the scores that are NOT on Monday (Hint – look up the ~ operator)

In [158]:
monday_bitmap = days == "Mon"
not_monday_bitmap = days != "Mon"

print(scores[:,~monday_bitmap])
print(scores[:,not_monday_bitmap])

[[ 8.75  8.   10.    7.75]
 [ 8.   10.    8.75  7.25]]
[[ 8.75  8.   10.    7.75]
 [ 8.   10.    8.75  7.25]]


#### 11) Select the scores that were on Tuesday or Thursday

In [159]:
t_bitmap = days == "Tue"
th_bitmap = days == "Thu"
t_or_th_bitmap = np.logical_or(t_bitmap, th_bitmap)

print(scores[:,t_or_th_bitmap])

[[ 8.75 10.  ]
 [ 8.    8.75]]


#### 12) Show the minimum and maximum scores for the entire array of scores

In [160]:
print("Minimum of scores:", np.min(scores))
print("Maximum of scores:", np.max(scores))

Minimum of scores: 7.25
Maximum of scores: 10.0


#### 13) Show the minimum scores for each week as a new array. The result should have the same dimensions (hint – use the keepdims parameter of np.min). Your result should be something like:

In [161]:
print("Minimum of scores each week:")
print(np.min(scores, axis=1, keepdims=True))

Minimum of scores each week:
[[7.75]
 [7.25]]


#### 14) Report the day that the maximum score occurred each week. (HINT: use argmax and use that result to index days.)

In [162]:
max_indices = np.expand_dims(np.argmax(scores, axis=1), axis=1)
print("Maximum score at index for each week:")
print(max_indices, "\n")

print(np.take_along_axis(scores, max_indices, axis=1))

Maximum score at index for each week:
[[3]
 [2]] 

[[10.]
 [10.]]


#### 15) Report the mean of the scores of each week

In [163]:
print("scores mean for each week:")
print(np.mean(scores, axis=1, keepdims=1))

scores mean for each week:
[[8.8]
 [8.6]]


#### 16) Suppose the lowest score was dropped from each week. Report the mean of each week, but without the minimum score for that week.

In [164]:
min_index = np.expand_dims(np.argmin(scores, axis=1), axis=1)
print("Minimum score at index for each week:")
print(min_index, "\n")

new_scores = np.delete(scores, min_index, axis=1)
print("scores after dropping minimum:")
print(new_scores, "\n")

print("scores mean for each week after dropped:")
print(np.mean(new_scores, axis=1, keepdims=1))

Minimum score at index for each week:
[[4]
 [4]] 

scores after dropping minimum:
[[ 9.5   8.75  8.   10.  ]
 [ 9.    8.   10.    8.75]] 

scores mean for each week after dropped:
[[9.0625]
 [8.9375]]


#### 17) Convert the scores to fall on a scale from 0-100 instead of 0-10. Show the result.

In [165]:
scores = scores * 10
print(scores)

[[ 95.   87.5  80.  100.   77.5]
 [ 90.   80.  100.   87.5  72.5]]


#### --- Random X ---

In [213]:
np.random.seed(1234)
X = np.random.randint(1,100,50).reshape((10,5))
print(X)

[[48 84 39 54 77]
 [25 16 50 24 27]
 [31 44 31 27 59]
 [93 70 81 74 48]
 [51 77 38 35 39]
 [68 12  1 76 81]
 [ 4  3 20 13 66]
 [76 82 15 72 61]
 [47 29 82 88 14]
 [97 13 70 96 32]]


#### 18) Select the first row of X

In [214]:
print(X[0])

[48 84 39 54 77]


#### 19) Select the last column of X

In [215]:
print(X[:,[-1]])

[[77]
 [27]
 [59]
 [48]
 [39]
 [81]
 [66]
 [61]
 [14]
 [32]]


#### 20) Select the first AND last column of X

In [216]:
print(X[:,[0,-1]])

[[48 77]
 [25 27]
 [31 59]
 [93 48]
 [51 39]
 [68 81]
 [ 4 66]
 [76 61]
 [47 14]
 [97 32]]


#### 21) Select every other row of X

In [217]:
print(X[::2])

[[48 84 39 54 77]
 [31 44 31 27 59]
 [51 77 38 35 39]
 [ 4  3 20 13 66]
 [47 29 82 88 14]]


#### 22) Show the transpose of X, but don't change X itself

In [218]:
print(X.T)
print(np.transpose(X))

[[48 25 31 93 51 68  4 76 47 97]
 [84 16 44 70 77 12  3 82 29 13]
 [39 50 31 81 38  1 20 15 82 70]
 [54 24 27 74 35 76 13 72 88 96]
 [77 27 59 48 39 81 66 61 14 32]]
[[48 25 31 93 51 68  4 76 47 97]
 [84 16 44 70 77 12  3 82 29 13]
 [39 50 31 81 38  1 20 15 82 70]
 [54 24 27 74 35 76 13 72 88 96]
 [77 27 59 48 39 81 66 61 14 32]]


#### 23) Select the first column of X and set the result to Y.

In [219]:
Y = X[0]

#### 24) Increment the first value of Y, then show the corresponding value of X. Did both values in X and Y change? THIS IS AN IMPORTANT OBSERVATION WHEN DEALING WITH SELECTING DATA!

In [220]:
Y[0] += 1
print(Y, "\n")
print(X)

"""
The value changed in both Y and X when only Y is incremented
   we know now that Y is not a copy, but just another memory
   pointer to the same array but with different partitioning
"""

[49 84 39 54 77] 

[[49 84 39 54 77]
 [25 16 50 24 27]
 [31 44 31 27 59]
 [93 70 81 74 48]
 [51 77 38 35 39]
 [68 12  1 76 81]
 [ 4  3 20 13 66]
 [76 82 15 72 61]
 [47 29 82 88 14]
 [97 13 70 96 32]]


#### 25) Repeat exercise 23, but ensure that Y is assigned a copy of the selected data. Increment the first value of Y again and ensure that the corresponding value of X did not change.

In [221]:
Y = X[0].copy()
Y[0] += 1

print(Y, "\n")
print(X)

[50 84 39 54 77] 

[[49 84 39 54 77]
 [25 16 50 24 27]
 [31 44 31 27 59]
 [93 70 81 74 48]
 [51 77 38 35 39]
 [68 12  1 76 81]
 [ 4  3 20 13 66]
 [76 82 15 72 61]
 [47 29 82 88 14]
 [97 13 70 96 32]]


#### 26) Create an array that contains the sequence of numbers 0, 0.1, 0.2, ... 9.8, 9.9 using arange, as a 10x10 matrix, stored as X.

In [222]:
X = np.arange(start=0, stop=10, step=0.1).reshape((10,10))
print(X)

[[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
 [1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
 [2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
 [3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9]
 [4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]
 [5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9]
 [6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9]
 [7.  7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9]
 [8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9]
 [9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]]


#### 27) Set the RNG seed to 1234. Then create an array X of 100 uniformly distributed numbers, with all values between 1.0 and 10.0. Then, show the mean, the median, the minimum and maximum values of X.

In [223]:
np.random.seed(1234)
X = np.random.uniform(low=1.0, high=10.0, size=100)
print("Mean of X:",np.mean(X))
print("Median of X:",np.median(X))
print("Minimum of X:",np.min(X))
print("Maximum of X:",np.max(X))

Mean of X: 5.665266170909222
Median of X: 5.827284349552116
Minimum of X: 1.0558766492841647
Maximum of X: 9.928733195695253


#### 28) Define what is meant by a normal distribution. What are the parameters of a normal distribution?

A normal distribution can be represented as a bell curve, the values are not uniformly distributed, the values are distributed in a way that have more values closer to the mean.
This then means that there is also a standard deviation that comes with this distribution, this number represents how the spread of data looks and how far the points are to the mean.

#### 29) In simple terms, using a normal distribution, what does the Law of Large Numbers tell us?

It tells us that with a high amount of input, most of the data should pool around the mean and values further away from the mean will be less common.

#### 30) Write a function called test_normal_dist. The purpose of this function is to evaluate the law of large numbers. It should have four parameters:    mu = mean of distribution sd = standard deviation vec_length = length of the vector to generate randomly from a normal distribution, with mu and sd as parameters num_trials = number of times to repeat the experiment

In [293]:
def test_normal_dist(mu, st, vec_length, num_trials):
    np.random.seed(1234)
    total_dev = 0
    for _ in range(num_trials):
        rand = np.random.normal(loc=mu, scale=st, size=int(vec_length))
        mean = np.mean(rand)
        total_dev += np.abs(mean) - mu
    return total_dev / num_trials

#### 31) Use test_normal_dist to obtain the deviation for vector lengths of 10, 100, 1000, 10000, and 100000. Use a fixed number of trials of 100 for each experiment. Report the results as a numpy array with two dimensions. the first being the vector length, and the second being the average deviation resulting from your test_normal_dist function. Your resulting array should look like:

In [332]:
test_vals = np.array([[10,0.0], [100,0.0], [1000,0.0], [10000,0.0], [100000,0.0]])

for i in range(len(test_vals)):
    vec_len = test_vals[i][0]
    result = test_normal_dist(100, 50, vec_len, 100)
    test_vals[i][1] = result

np.set_printoptions(suppress=True)
print(test_vals)

[[    10.         0.787]
 [   100.         0.806]
 [  1000.         0.049]
 [ 10000.        -0.016]
 [100000.         0.004]]
