# lab 01 - Getting Started 
Name: Robb Alexander    
Class: CSCI349    
Semester: 2021SP    
Instructor: Brian King

#### 2. Did you read the syllabus? All of it? Do you agree to abide by the cheating rules? Write a sentence clearly indicating your commitment to not cheating.

I read all of the syllabus that wasn't a copy/pasted section. I agree that I will never cheat or do anything that violates the terms set in the syllabus.

#### 3. What are you hoping to get out of this course?

I hope to learn about the practical uses of data science/mining. I have already taken a machine learning class, but it was all math and theory of different models. I hope this class can encompass the missing.    
I also never had you as a professor for 205 due to your sabbatical, so I missed out on that life altering experience and hope this course is a good enough substitute. 

#### 4. Print the Python version (available in sys package)

In [8]:
import sys
print(sys.version)

3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ]


#### 5. Create a Python list of 10000 random integers in the range 1 to 100, using the random package. Name the list x_list.

In [10]:
import random
x_list = [random.randint(1,100) for _ in range(10000)]

#### 6. What is the minimum value of x_list? What is the max value? What is the mode?

In [11]:
from statistics import mode
print("The minimum of x_list is:", min(x_list))
print("The maximum of x_list is:", max(x_list))
print("The mode of x_list is:", mode(x_list))

The minimum of x_list is: 1
The maximum of x_list is: 100
The mode of x_list is: 85


#### 7. Write a function to take a list of numbers as a parameter, and return the average of the list. Then, use your function to report the average value of x_list, printed as a float with 2 places of precision.

In [12]:
def average(nums):
    total = sum(nums)
    n = len(nums)
    avg = total / n
    return round(avg, 2)

print(average(x_list))

50.41


#### 8. Create a list called x_hist that represents a histogram, i.e. a distribution of the numerical data, of x_list. Each entry in x_hist should contain the range of data in widths of 10. So, x_hist[0] represents the frequency of numbers between 1-10, x_hist[1] is the frequency of numbers between 11-20, and so on. Be sure to print x_hist at the end.

In [33]:
from collections import Counter
counts = Counter(x_list)
x_hist = [0] * 10

for num, count in counts.items():
    index = (num - 1) // 10
    x_hist[index] += count

print(x_hist)

[1028, 1001, 975, 1020, 1004, 962, 1010, 973, 1008, 1019]


#### 9. What is numpy? What are its strengths? Does it have any weaknesses?

Numpy is a library that specializes in math with functions and data structures that help in matrixes and array computation. This is useful for large datasets, and most notably uses `np.array()` instead of a python [] array; this improves the speed due to what they call vectorization.
Personally the weakness that I think numpy has is the convolutedness of the array functions and it is not beginner friendly. You need to have precise ways to construct and transform a [] list before passing it in. The complexity makes it only fit for more formal research/projects.

#### 10. Import the numpy package as np and print the numpy version

In [63]:
import numpy as np
print("numpy version:", np.__version__)

numpy version: 1.19.2


#### 11. What is the primary object type in numpy? Can it store data of different types? Discuss.

The primary type is the `np.array()` and it can be used to create vectors and matrixes that then can be used with Scikit learn and other packages to use tricks in linear algebra.
To achieve different data types in the same `np.array` you need to convert the data into the object data type.


#### 12. Discuss the types of data available in numpy. You need not list every type. Just generalize, and discuss how the type system is different than the built-in types int and float in Python.

You have the classic `string`, `int`, `float`, and `boolean`. There is also the extra dtype that represents complex numbers, which uses `complex` as a key word.
The major difference between python3 and numpy primitive numbers is that numpy uses static sized numbers while python3 uses flexible sized numbers. This is done to optimize speed for modern day computation while also allowing for memory swapping of same sized dtypes. Classic cs, trading space for time.

#### 13. Create a numpy array from x_list. Reassign it as x_list. Show the contents.

In [62]:
x_list2 = x_list.copy()
x_list = np.array(x_list)
print("x_list is now a",type(x_list).__name__)
print(x_list)
# to print all content, change np.set_printoptions to inf

x_list is now a ndarray
[85. 58. 63. ... 47. 55. 99.]


#### 14. Redo the previous exercise, but set the data type of each value to 'float32'

In [46]:
x_list = np.array(x_list2, dtype='f')
print(x_list)

[85. 58. 63. ... 47. 55. 99.]


#### 15. Create a length 10 integer array filled with zeros

In [49]:
# array = [0] * 10
# array = [0 for _ in range(10)]

array = np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 16. Create a float array of 3 rows and 4 columns, all initialized to one.

In [50]:
array = np.ones((3,4), dtype='f')
print(array)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### 17. Create an array of 20 values, evenly spaced between 1 and 3 (HINT – look at np.linspace)

In [52]:
array = np.linspace(start=1,stop=3,num=20)
print(array)

[1.         1.10526316 1.21052632 1.31578947 1.42105263 1.52631579
 1.63157895 1.73684211 1.84210526 1.94736842 2.05263158 2.15789474
 2.26315789 2.36842105 2.47368421 2.57894737 2.68421053 2.78947368
 2.89473684 3.        ]


#### 18. Set the numpy random seed to the value 12345, then create a 10 x 5 array of random integers on the interval [10, 20)

In [64]:
np.random.seed(12345)
array = np.random.randint(low=10, high=20, size=(10,5), dtype='i')
print(array)

[[12 15 11 14 19]
 [15 12 11 16 11]
 [19 17 16 10 12]
 [19 11 12 16 17]
 [17 17 18 17 11]
 [17 14 10 13 15]
 [17 13 11 15 12]
 [15 13 18 15 12]
 [15 13 10 16 18]
 [10 15 16 18 19]]
